server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    name: deliversystem
    url: jdbc:mysql://localhost:3306/deliversystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.summer.entity
